#!/bin/sh

ssh app@104.236.11.72 <<EOF

  rm -Rf ~/openFDAWebApp
  git clone https://github.com/shyamrock/openFDAWebApp.git
  cd ~/openFDAWebApp
  npm install --production
  forever restartall
  exit
EOF
