#!/bin/sh

ssh app@104.236.11.72 <<EOF
 rm -Rf openFDAWebApp
 forever stopall
 git clone https://github.com/shyamrock/openFDAWebApp.git
 cd ~/openFDAWebApp
 npm install --production
 grunt build
 forever start app.js
  exit
EOF
