#!/bin/sh

ssh app@104.236.11.72 <<EOF
  forever stopall
  sudo rm -Rf ~/openFDAWebApp
  git clone https://github.com/shyamrock/openFDAWebApp.git
  cd ~/openFDAWebApp
  npm install --production
  forever start app.js --port=80 --prod
  exit
EOF
